cups_profile/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('my_info.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

my_info/urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'my_info.views.info_page', name='home'),
    url(r'^requests/$', 'my_info.views.logged_requests_page', name='logged_requests_page'),
    url(r'^edit_contacts/$', 'my_info.views.edit_contacts', name='edit_contacts'),
    url(r'^edit_contacts_inline/$', 'my_info.views.inline_contacts_edit', name='inline_contacts_edit'),
)

my_info/models.py
#-*- coding:utf-8 -*-
from django.conf import settings
from django.db import models
from django.db.utils import DatabaseError
from django.db.models.signals import post_save, post_delete

import os
from PIL import Image


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=75)
    birth_date = models.DateField(
        auto_now=False, auto_now_add=False)
    bio = models.TextField()
    email = models.EmailField(max_length=75)
    jabber = models.CharField(max_length=50)
    skype = models.CharField(max_length=50)
    extra_contacts = models.TextField(null=True, blank=True)
    photo = models.ImageField(upload_to='img/', blank=True, null=True)

    def save(self, photo_size=(380, 500)):
        super(Contact, self).save()
        if self.photo:
            filename = os.path.split(settings.DEPLOY_DIR)[0] + self.photo.url
            image = Image.open(filename)
            image.thumbnail(photo_size, Image.ANTIALIAS)
            image.save(filename)

    def __unicode__(self):
        return "%s %s" % (self.last_name, self.first_name)


class LoggedRequest(models.Model):
    url = models.CharField(max_length=255)
    ip = models.CharField(max_length=20)
    request_type = models.CharField(max_length=4)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    priority = models.IntegerField(default=0)

    def __unicode__(self):
        return "Request: %s From: %s At: %s" % (
            self.request_type, self.ip, self.timestamp)


class ModelChangeLog(models.Model):
    CREATED = 'created'
    DELETED = 'deleted'
    ALTERED = 'altered'

    app_label = models.CharField(max_length=255)
    model_name = models.CharField(max_length=255)
    action = models.CharField(max_length=7)
    timestamp = models.DateTimeField(auto_now=True)

    @classmethod
    def log_record(cls, instance, action):
        if isinstance(instance, ModelChangeLog):
            return
        try:
            log_record = ModelChangeLog(
                app_label=instance._meta.app_label,
                model_name=instance.__class__.__name__,
                action=action
            )
            log_record.save()
        except DatabaseError:
            pass

    def __unicode__(self):
        return "%s:%s - %s" % (self.app_label, self.model_name, self.action)


def log_create_alter(sender, instance, created, **kwargs):
    ModelChangeLog.log_record(
        instance,
        ModelChangeLog.CREATED if created else ModelChangeLog.ALTERED
    )


def log_deleted(sender, instance, **kwargs):
    ModelChangeLog.log_record(instance, ModelChangeLog.DELETED)


post_save.connect(log_create_alter, dispatch_uid='log_create_alter')
post_delete.connect(log_deleted, dispatch_uid='log_deleted')

my_info/forms.py
#-*- coding:utf-8 -*-
from django.forms import ModelForm

from my_info.models import Contact
from my_info.widgets import MyDatePicker


class ContactForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget = MyDatePicker(
            params="dateFormat: 'yy-mm-dd', changeYear: true,"
            " defaultDate: '-16y', yearRange: 'c-40:c+16'",
            attrs={'class': 'datepicker', }
        )

    class Meta:
        model = Contact

my_info/views.py
#-*- coding:utf-8 -*-
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse

from annoying.decorators import render_to, ajax_request
from annoying.functions import get_object_or_None
import json

from my_info.models import Contact, LoggedRequest
from my_info.forms import ContactForm


SORTING = {
    'timestamp': "Timestamp ASC",
    '-timestamp': "Timestamp DESC",
    'priority': "Priority ASC",
    '-priority': "Priority DESC"
}


@require_GET
@render_to('my_info/home.html')
def info_page(request):
    my_contacts = get_object_or_404(Contact, pk=1)
    return {'contacts': my_contacts}


@require_GET
@render_to('my_info/requests.html')
def logged_requests_page(request):

    queryset = LoggedRequest.objects.all()
    ordering = 'timestamp'

    if 'ordering' in request.GET and request.GET['ordering']:
        ordering = request.GET['ordering']
    requests = queryset.order_by(ordering)[: 10]

    return {'requests': requests, 'sorting': SORTING, 'active': ordering}


@login_required
@render_to('my_info/edit_contacts.html')
def edit_contacts(request):
    my_contacts = get_object_or_None(Contact, id=1)

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=my_contacts)
        response_dict = {}
        if request.is_ajax():
            if form.is_valid():
                form.save()
                response_dict['result'] = 'success'
            else:
                response_dict['result'] = 'error'
                errors = {}
                for error in form.errors:
                    errors[error] = form.errors[error][0]
                response_dict['form_errors'] = errors
            data = json.dumps(response_dict, ensure_ascii=False)
            return HttpResponse(data, mimetype='application/json')
        else:
            if form.is_valid():
                form.save()
                return redirect(reverse('home'))
    else:
        form = ContactForm(instance=my_contacts)

    return {'form': form, 'photo': my_contacts.photo}


@ajax_request
@require_POST
def inline_contacts_edit(request):
    if not request.is_ajax():
        response = HttpResponse('Ajax Required')
        response.status_code = 400
        return response

    contact = get_object_or_404(Contact, id=1)

    response = {'result': 'success'}
    fields, contacts_id = None, request.POST.get('instance_id', None)
    new_photo = None

    if 'fields' in request.POST and request.POST['fields']:
        fields = json.loads(request.POST['fields'])
    if 'photo' in request.FILES and request.FILES['photo']:
        new_photo = request.FILES['photo']

    if fields and contacts_id:
        try:
            Contact.objects.filter(id=contacts_id).update(**fields)
        except Exception as e:
            response['result'] = 'error'
            response['msg'] = str(e)
    elif not fields and contacts_id:
        response['result'] = 'empty'
        response['msg'] = "Nothing to update..."
    if new_photo:
        try:
            contact.photo = new_photo
            contact.save()
        except Exception as e:
            response['result'] = 'error'
            response['msg'] = str(e)

    return response

cups_profile/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/foundation.css" />
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block extra_css %}
    {% endblock %}
    <script type="text/javascript"
        src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.js"></script>
    <script type="text/javascript">
        window.myinfo = {};
    </script>
    <script src="{{ STATIC_URL }}js/vendor/modernizr.js"></script>
    {% block extra_js %}
    {% endblock %}
  </head>
  <body>
    <div class="row">
        <h1 class="text-left">42 Coffee Cups Test Assignment</h1>
    </div>
  {% block body %}
  {% endblock %}
    <ul class="breadcrumbs">
        {% block panel %}{% endblock %}
    </ul>
  </body>
</html>

cups_profile/templates/my_info/edit_contacts.html
{% extends "base.html" %}

{% block title %}Contacts Edit Page{% endblock %}

{% block extra_css %}
    <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/smoothness/jquery-ui.css" rel="Stylesheet" />
{% endblock %}

{% block extra_js %}
    <script src="http://malsup.github.com/jquery.form.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/edit_contacts_page.js"></script>
{% endblock %}

{% block body %}

<form id="editmyinfo" enctype="multipart/form-data" action="{% url edit_contacts %}" method="POST">
  <div class="row panel radius">
    {% csrf_token %}
    <div class="large-5 columns">
      <div id="name">
        <label>{{ form.first_name.label}}: {{ form.first_name }}</label>
      </div>
      <div id="surname">
        <label>{{ form.last_name.label }}: {{ form.last_name }}</label>
      </div>
      <div id="birth_date">
        <label>{{ form.birth_date.label }}: {{ form.birth_date }}</label>
      </div>
      <div id="my_photo">
        <label>{{ form.photo.label }}:</label>
        {{ form.photo }}
      </div>
      <div class="clr"></div>
      <div class="th" id="img_container"><img id="img_prev" src="{% if photo %}{{MEDIA_URL}}{{ photo }}{% else %}http://placehold.it/380x500{% endif %}" alt="Image preview" /></div>
    </div>

    <div class="large-5 columns">
      <div id="email">
        <label>{{ form.email.label }}: {{ form.email }}</label>
      </div>
      <div id="jabber">
        <label>{{ form.jabber.label }}: {{ form.jabber }}</label>
      </div>
      <div id="skype">
        <label>{{ form.skype.label }}: {{ form.skype }}</label>
      </div>
      <div id="other_cont">
        <label>{{ form.extra_contacts.label }}:<br/> {{ form.extra_contacts }}</label>
      </div>
      <div id="bio">
        <label>{{ form.bio.label }}:<br/> {{ form.bio }}</label>
      </div>
    </div>
  </div>

  <div class="row panel radius">
  <div class="large-5 columns">

    <ul class="button-group">
      <li><button class="button" id="savebutton" type="submit">Submit</button></li>
      <li class="button alert"><a href="{% url home %}">Cancel</a></li>
    </ul>
  </div>
  <div class="large-5 columns">
    <label class="label text-large" id="error_message">Fill the form and press Submit button</label>
  </div>
  </div>
</form>

{% endblock %}

{% block panel %}
    <a href="{% url logged_requests_page %}">Requests</a>
{% endblock %}

cups_profile/templates/my_info/home.html
{% extends "base.html" %}
{% load admin_edit_link %}

{% block title %}Contacts{% endblock %}

{% block extra_css %}
  <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/smoothness/jquery-ui.css" rel="Stylesheet" />
{% endblock %}


{% block extra_js %}

  {% if user.is_superuser  %}<script type="text/javascript" src="{{ STATIC_URL }}js/in-line_edit.js"></script>{% endif %}
  <script type="text/javascript" src="{{ STATIC_URL }}js/csrf.js"></script>
  <script src="http://malsup.github.com/jquery.form.js"></script>
  <script type="text/javascript">
      window.myinfo['instance_id'] = {{ contacts.id }};
      window.myinfo['inline_edit_url'] = {% url inline_contacts_edit %}
  </script>
{% endblock %}

{% block body %}
<ul class="breadcrumbs">
  {% if user.is_authenticated %}
    <li><a href="{% url edit_contacts %}">Edit</a></li>
    <li><a href="{% edit_link contacts %}">(admin)</a></li>
    <li><a href="{% url logout %}">Logout</a></li>
  {% else %}
    <li><a href="{% url login %}">Login</a></li>
  {% endif %}
</ul>

<div class="row panel callout">
  <ul class="no-bullet">
    <li><em>To make changes you need to be <b>logged in</b> and to be a <b>superuser</b>;</em></li>
    <li><em>To modify any field value - just click on it;</em></li>
    <li><em>To restore old value of any field (before saving): place focus in it and hit <b>Esc</b>;</em></li>
    <li><em>To save your changes - press <b>Ctrl+Enter</b>;</em></li>
    <li><em>To change photo - just select it by clicking "Change Photo.." link;</em></li>
    <li><em>Photo saves automatically after new file selection;</em></li>

  </ul>
</div>

<div class="row">
  <div data-alert class="alert-box success radius" style="display:none;">
    <div class="js-alert-text"></div>
    <a href="#" class="close">&times;</a>
  </div>
</div>

<div class="row panel">
    <div class="large-6 columns">
    <p class="large-4 columns"> <label> Name: </label><div id="first_name" class="field">{{ contacts.first_name }}</div></p>
    <p class="large-4 columns"><label> Last Name: </label><div id="last_name" class="field">{{ contacts.last_name }}</div></p>
    <p class="large-4 columns"><label>Date of Birth:</label><div id="birth_date" class="field">{{ contacts.birth_date|date:"Y-m-d" }}</div><input type="hidden" value="{{ contacts.birth_date }}" /></p>
    <form id="photo-change-form" enctype="multipart/form-data" action="{% url inline_contacts_edit %}" method="POST"><div class="large-10 columns">{% csrf_token %}
    {% if user.is_superuser %}<small><a class="showme" id="js-select-photo" href="#">Change Photo..</a></small>{% else %}<label>Photo:</label>{% endif %}
      <div id="js-photo-controls" style="display:none;">
        <input type="file" name="photo" id="id_photo" />
      </div>
    </div></form>
      <img id="photo-frame" class="th" src="{% if contacts.photo %}{{ MEDIA_URL }}{{ contacts.photo }}{% else %}http://placehold.it/380x500{% endif %}">
    </div>


    <div class="large-6 columns">
      <p class="large-4 columns"><label>Email: </label><div id="email" class="field">{{ contacts.email }}</div></p>
      <p class="large-4 columns"><label>Jabber:</label> <div id="jabber" class="field">{{ contacts.jabber }}</div></p>
      <p class="large-4 columns"><label>Skype:</label> <div id="skype" class="field">{{ contacts.skype }}</div></p>

      <p class="large-4 columns"><label> Extra Contacts:</label>
      <div id="extra_contacts" class="multiline field" style="max-width:70%; overflow:auto;">{{ contacts.extra_contacts }}</div></p>
      <p class="large-4 columns"><label> Bio:</label>
      <div id="bio" class="multiline field" style="max-width:70%; overflow:auto;">{{ contacts.bio }}</div></p>
    </div>
</div>

</div>


{% endblock %}
{% block panel %}
  <li><a href="{% url logged_requests_page %}?ordering=-priority">Requests</a></li>
{% endblock %}

cups_profile/templates/my_info/requests.html
{% extends "base.html" %}

{% block title %} Request's Log {% endblock %}

{% block body %}


<div class="row">
    <h5>Sorting:</h5>
</div>
<div class="row">
    <ul class="breadcrumbs">
    {% for key, value in sorting.items %}
        <li> <a class="label {% if key == active %}success{% else %}secondary{% endif %}" href="{% url logged_requests_page %}?ordering={{ key }}">{{ value }}</a></li>
    {% endfor %}
    </ul>
</div>
<div class="row">
    <table>
        <thead>
            <th width="100" >Type</th>
            <th width="400">Requested Url</th>
            <th width="200">From IP</th>
            <th width="100">Priority</th>
            <th width="200">Timestamp</th>
        </thead>
        <tbody>
            {% for request in requests %}
            <tr>
                <td>{{ request.request_type }}</td>
                <td>{{ request.url }}</td>
                <td>{{ request.ip }}</td>
                <td> {{ request.priority }}</td>
                <td>{{ request.timestamp }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block panel %}
    <a href="{% url home %}">Home</a>
{% endblock %}